-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
	-- Notifications:
	['invalid_amount']          = 'Cantidad inválida',
	['invalid_string']          = 'Invalid String',
	['no_players_nearby']		= 'No hay jugadores cerca!',
	['no_vehicle_nearby']       = 'No hay vehiculos cerca!',
	['not_enough_money']        = 'No tienes suficiente dinero.',
	['must_be_driver']			= 'Debes estar en el asiento del conductor',
	['action_not_possible']		= 'Esta acción no es posible dentro de un vehiculo.',
	['already_holding_obj']		= 'Ya estas cargando un objeto, por favor ponlo en el suelo.',

	['mech_shop_purchased']     = 'Compraste un ~b~taller de mecánicos~s~ y pagaste ~g~$%s~s~',
	['mech_shop_renamed']       = '~g~Taller de mecánico ha sido renombrado.~s~',
	['mech_shop_sold']          = 'Vendiste tu ~b~taller de mecánicos~s~ y recibiste ~g~$%s~s~',
	['get_account_balance']  	= 'Saldo actual: ~g~$%s~s~.',

	['storage_inv_empty']       = 'El inventario de almacenamiento está vacio.',
	['storage_deposited_x']     = 'Depositaste: %sx %s al almacenamiento.',
	['not_enough_items']        = 'No hay suficientes artículos para depositar.',
	['storage_withdrew_x']      = 'Retiraste: %sx %s del almacenamiento.',
	['too_high_count']          = 'La cantidad solicitada es demasiado alta en comparación con el inventario de almacenamiento',
	['not_enough_materials']    = 'Necesitas más materiales, mira la receta',
	['crafting_in_progress']    = 'Crafteando, por favor espere!',
	['you_crafted_x_item']    	= 'Crafteo realizado: %s.',

	['car_jack_carry']			= 'Necesitas llevar un gato hidráulico contigo.',
	['too_far_from_carjack']  	= 'Te alejaste demasiado del gato hidráulico...',
	['analyze_not_possible']  	= 'El vehículo debe estar levantado sobre el gato hidráulico para realizar un análisis..',
	['no_body_replace_needed']	= 'No se requiere reemplazo para la carrocería del vehículo - la carrocería ahora está en la mejor posición.',
	['analyze_to_inst_parts']	= 'Analizar el vehículo antes de instalar piezas.',
	['body_install_ongoing']	= 'Termina la instalación de la carrecería actual',
	['too_far_from_vehicle']  	= 'Te alejaste demasiado del vehículo...',
	['body_inst_not_possible']	= 'Levante el vehículo con un gato hidráulico y analice el vehículo antes de instalar las piezas.',
	['all_doors_intact']        = 'Todas las puertas están reparadas e intactas..',
	['hood_already_installed']  = 'El capó ya esta instalado.',
	['trunk_already_installed'] = 'El maletero ya esta instalado.',
	['all_wheels_intact']       = 'Todas las llantas están reparadas e intactas..',
	['all_body_repairs_done']	= 'Todas las reparaciones de carrocería están hechas. Baje el vehículo!',

	['lift_cannot_go_higher']	= 'El ascensor no puede subir más!',
	['lift_cannot_go_lower']	= 'El ascensor no puede bajar más!',
	['already_inspecting_veh']	= 'Ya está inspeccionando el vehículo, complete la inspección.',
	['veh_must_be_inspected']	= 'Inspeccione el vehículo antes de reparar las piezas.',
	
	['health_part_exceeded']    = 'El valor de la pieza no puede exceder 10.0',
	['not_decrease_health_val'] = 'No puede disminuir el valor actual de la pieza.',
	['not_decrse_or_same_val']  = 'No puede disminuir o establecer el mismo valor de la pieza, debe ser un valor más alto!',
	['need_more_materials']     = 'Necesita más materiales para reparar el valor seleccionado.',
	['you_rep_health_part']     = 'Reparaste: %s. Su nuevo valor es: %s',
	['veh_engine_repaired']     = 'El motor del vehículo ha sido reparado..',
	['veh_engine_no_repair']    = 'El motor no requiere ninguna reparación..',
	['veh_engine_functional']   = 'El vehículo está completamente funcional. Reparaciones de piezas requieren un mecánico.',
	['repair_kit_broke']        = 'El kit de reparación se destruyó.',
	['repairkit_veh_repaired']  = 'El motor del vehículo ya está reparado, diríjase al taller mecánico más cercano.',
	
	['npc_no_calls_available']	= 'No hay llamadas disponibles en este momento.',
	['npc_shout_msg']           = '¡Hola! ¿Puedes reparar mi auto por favor?',
	['npc_need_repair_kit']     = 'Necesitas un kit de reparación.',
	['npc_kit_broke']           = 'Durante la reparación, su kit se rompió.',
	['npc_veh_repaired']        = 'Vehículo reparado. Recoge el efectivo del NPC.',
	['npc_thanking_msg']        = 'Muchas gracias, adios!',
	['npc_cancel_job_death']    = '¡Moriste! El trabajo ha sido cancelado.',
	['npc_job_cancel_by_ply']   = 'Cancelaste tu trabajo actual.',
	['npc_job_cash_reward']     = 'Recibiste: ~g~$%s~s~ departe del NPC.',
	
	-- Draw Texts:
	['draw_mechanic_menu']      = '~r~[E]~s~ Menú Mecánico',
	['draw_shop_owned']         = 'Taller de Mecánica no está en venta',
	['draw_buy_mech_shop']      = '~r~[E]~s~ Comprar Taller de Mecánica [~g~$%s~s~]',
	['draw_shop_own_one']       = 'Solo puedes tener un taller de mecánica',
	['draw_open_storage']      	= '~r~[E]~s~ Inventario',
	['draw_open_workbench']     = '~r~[E]~s~ Mesa de trabajo',
	['draw_raise_jack']     	= 'Levanta el gato hidráulico',
	['draw_lower_jack']     	= 'Baja el gato hidráulico',
	['draw_analyze_veh_body']	= 'Analizar la carrocería del vehículo',
	['draw_car_jack']			= '~r~[E]~s~ %s',
	['draw_analyze_here']       = '~r~[E]~s~ Analiza aquí',
	['draw_install_b_part']     = '~r~[G]~s~ Instalar carrocería',
	['draw_park_on_lift']       = '~r~[E]~s~ Estaciona en el ascensor',
	['draw_lift_occupied']     	= 'Ascebsir ocupado',
	['draw_no_veh_control']     = 'Control no disponible',
	['draw_veh_remove_or_move']	= '~r~[G]~s~ Quitar vehículo | ~y~[Flecha arriba/abajo]~s~ Mover vehículo',
	['draw_inspect_vehicle']	= '~b~[E]~s~ Inspeccionar vehículo',
	['draw_inspect_here']		= '~r~[E]~s~ Inspeccionar aquí',
	['health_rep_here']         = '~r~[E]~s~ Reparar aquí',
	['draw_repair_engine']		= '~r~[E]~s~ Reparar motor',
	['draw_quick_repair']		= '~r~[G]~s~ Reparar vehículo',
	['draw_npc_repair_veh']     = '~r~[E]~s~ Reparar vehículo NPC',
	['draw_npc_collect_cash']   = '~r~[E]~s~ Recoger dinero',
	['draw_repair_kit']   		= '~r~[E]~s~ Usar kit de reparación',

	-- Progress Bars:
	['progb_lowering_jack']		= 'Bajando gato hidráulico',
	['progb_raising_jack']		= 'Subiendo gato hidráulico',
	['progb_analyzing_body']	= 'Analizando carrocería',
	['progb_inspecting_veh']	= 'Inspeccionando vehículo',
	['progb_lift_repair_veh']	= 'Reparando: %s',
	['progb_crafting_item']     = 'Crafteando: %s',
	['progb_reparing_veh']     	= 'Reparando vehículo',
	['progb_npc_veh_repair']    = 'Reparando vehículo NPC',
	['progb_npc_collect_cash']	= 'Recogiendo dinero',

	-- Blips:
	['npc_repair_job']			= 'NPC Repair Job'
}