AddTextEntry("WEAPON_AK47", "AK-47")
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_DE", "Desert Eagle")
AddTextEntry("WEAPON_FNX45", "FN FNX45")
AddTextEntry("WEAPON_GLOCK17", "Glock17")
AddTextEntry("WEAPON_HUNTINGRIFLE", "Hunting Rifle")
--AddTextEntry("WEAPON_M4", "M4")
AddTextEntry("WEAPON_M9", "M9A3")
AddTextEntry("WEAPON_M1911", "M1911")
AddTextEntry("WEAPON_MAC10", "MAC-10")
AddTextEntry("WEAPON_SCARH", "SCAR-H")
AddTextEntry("WEAPON_SHIV", "Shiv")
AddTextEntry("WEAPON_KATANA", "Katana")
--AddTextEntry("WEAPON_UZI", "UZI")
AddTextEntry("WEAPON_SLEDGEHAMMER", "Sledge Hammer")
AddTextEntry("WEAPON_MP9", "MP9")
AddTextEntry("WEAPON_M110", "M110")
AddTextEntry("WEAPON_HK416", "HK-416")
AddTextEntry("WEAPON_MP5", "MP5")


